import React, { useMemo, useState } from 'react';
import type { Child } from './types/parent';
import type { ChildWorkspace, HomeworkItem, TeachingPlanItem, TeacherProfile, TestExam } from './learningWorkspace';

type Props = { mode: 'teachers' | 'subjects' | 'tests' | 'teaching' | 'homework'; children: Child[]; active: string; setActive: (id: string) => void; workspace: ChildWorkspace; setWorkspace: (next: ChildWorkspace) => void };

export function ParentLearningTools({ mode, children, active, setActive, workspace, setWorkspace }: Props) {
  const child = children.find(c => c.id === active) || children[0];
  const [text, setText] = useState('');
  const [subject, setSubject] = useState(workspace.subjects[0] || '');
  const [date, setDate] = useState('');
  const [topic, setTopic] = useState('');

  const selectedTeacher = useMemo(() => workspace.teachers.find(t => t.name.toLowerCase() === text.trim().toLowerCase()), [workspace.teachers, text]);
  if (!child) return <div className="coming-section panel"><div className="coming-icon">👧</div><h2>Add a child first</h2><p>These learning controls become available after a child is added.</p></div>;

  const saveTeacher = () => {
    const name = text.trim(); if (!name) return;
    const teacher: TeacherProfile = { id: `teacher-${name.toLowerCase().replace(/\s+/g, '-')}`, name, role: 'Personal AI Teacher', subjects: subject ? [subject] : workspace.subjects.slice(0, 3), style: 'Warm, patient and step-by-step', enabled: true };
    const others = workspace.teachers.filter(t => t.id !== teacher.id);
    setWorkspace({ ...workspace, teachers: [...others, teacher] }); setText('');
  };
  const addSubject = () => { const value = text.trim(); if (!value || workspace.subjects.some(s => s.toLowerCase() === value.toLowerCase())) return; setWorkspace({ ...workspace, subjects: [...workspace.subjects, value] }); setText(''); };
  const removeSubject = (value: string) => setWorkspace({ ...workspace, subjects: workspace.subjects.filter(s => s !== value), today: workspace.today.filter(t => t.subject !== value), homework: workspace.homework.filter(h => h.subject !== value) });
  const addTest = () => { if (!text.trim() || !subject || !date) return; const item: TestExam = { id: crypto.randomUUID(), title: text.trim(), subject, date, type: 'Gurukulam', topics: topic.trim() || 'Full chapter review', status: 'Upcoming' }; setWorkspace({ ...workspace, tests: [...workspace.tests, item] }); setText(''); setTopic(''); setDate(''); };
  const addTeaching = () => { if (!subject || !topic.trim()) return; const item: TeachingPlanItem = { id: crypto.randomUUID(), subject, topic: topic.trim(), duration: 25, objective: `Understand and practise ${topic.trim()}.`, completed: false }; setWorkspace({ ...workspace, today: [...workspace.today, item] }); setTopic(''); };
  const addHomework = () => { if (!subject || !text.trim() || !date) return; const item: HomeworkItem = { id: crypto.randomUUID(), subject, title: text.trim(), instructions: topic.trim() || 'Complete the assigned practice and review your answers.', dueDate: date, status: 'Pending' }; setWorkspace({ ...workspace, homework: [...workspace.homework, item] }); setText(''); setTopic(''); setDate(''); };
  const selectChild = <select className="timetable-child" value={child.id} onChange={e => setActive(e.target.value)}><option value="" disabled>Select child</option>{children.map(c => <option key={c.id} value={c.id}>{c.name || 'Unnamed child'}</option>)}</select>;

  return <section className="parent-section"><div className="section-heading"><div><small>PARENT CONTROL</small><h1>{mode === 'teachers' ? '👨‍🏫 Teacher Details' : mode === 'subjects' ? '📚 Subjects' : mode === 'tests' ? '📝 Test / Exam' : mode === 'teaching' ? "📖 Today's Teaching" : "🏠 Kid's Homework"}</h1><p>Configure learning for <strong>{child.name}</strong>. Changes apply only to this child.</p></div>{selectChild}</div>
    {mode === 'teachers' && <><div className="panel"><h2>Add / update teacher</h2><div className="subject-add-row"><input value={text} onChange={e => setText(e.target.value)} placeholder="Teacher name"/><select value={subject} onChange={e => setSubject(e.target.value)}><option value="">Subjects</option>{workspace.subjects.map(s => <option key={s}>{s}</option>)}</select><button className="primary" onClick={saveTeacher}>Save Teacher</button></div></div><div className="child-list">{workspace.teachers.map(t => <article className="child-row" key={t.id}><div><h3>👨‍🏫 {t.name}</h3><p>{t.role} · {t.subjects.join(', ') || 'No subjects assigned'}</p><span className="child-school">{t.style}</span></div><button className={t.enabled ? 'secondary' : 'primary'} onClick={() => setWorkspace({ ...workspace, teachers: workspace.teachers.map(x => x.id === t.id ? { ...x, enabled: !x.enabled } : x) })}>{t.enabled ? 'Enabled' : 'Enable'}</button></article>)}</div></>}
    {mode === 'subjects' && <><div className="panel"><h2>Manage subjects</h2><div className="subject-add-row"><input value={text} onChange={e => setText(e.target.value)} placeholder="New subject"/><button className="primary" onClick={addSubject}>＋ Add Subject</button></div></div><div className="subject-list">{workspace.subjects.map(s => <div className="subject-row" key={s}><strong>📘 {s}</strong><button className="danger" onClick={() => removeSubject(s)}>Remove</button></div>)}</div></>}
    {mode === 'tests' && <><div className="panel"><h2>Create school / Gurukulam assessment</h2><div className="form-grid"><label>Test name<input value={text} onChange={e => setText(e.target.value)} placeholder="e.g. Maths Chapter Test"/></label><label>Subject<select value={subject} onChange={e => setSubject(e.target.value)}>{workspace.subjects.map(s => <option key={s}>{s}</option>)}</select></label><label>Date<input type="date" value={date} onChange={e => setDate(e.target.value)}/></label><label>Topics<input value={topic} onChange={e => setTopic(e.target.value)} placeholder="Chapters / concepts"/></label></div><button className="primary" onClick={addTest}>＋ Schedule Test</button></div><div className="child-list">{workspace.tests.map(t => <article className="child-row" key={t.id}><div><h3>📝 {t.title}</h3><p>{t.type} · {t.subject} · {t.date}</p><span className="child-school">{t.topics}</span></div><button className="danger" onClick={() => setWorkspace({ ...workspace, tests: workspace.tests.filter(x => x.id !== t.id) })}>Delete</button></article>)}</div></>}
    {mode === 'teaching' && <><div className="panel"><h2>Plan today's teaching</h2><div className="form-grid"><label>Subject<select value={subject} onChange={e => setSubject(e.target.value)}>{workspace.subjects.map(s => <option key={s}>{s}</option>)}</select></label><label>Topic<input value={topic} onChange={e => setTopic(e.target.value)} placeholder="What should be taught today?"/></label></div><button className="primary" onClick={addTeaching}>＋ Add to Today's Teaching</button></div><div className="child-list">{workspace.today.map(t => <article className="child-row" key={t.id}><div><h3>📖 {t.subject}: {t.topic}</h3><p>{t.duration} minutes · {t.objective}</p></div><button className={t.completed ? 'secondary' : 'primary'} onClick={() => setWorkspace({ ...workspace, today: workspace.today.map(x => x.id === t.id ? { ...x, completed: !x.completed } : x) })}>{t.completed ? 'Completed' : 'Mark Complete'}</button></article>)}</div></>}
    {mode === 'homework' && <><div className="panel"><h2>Assign homework</h2><div className="form-grid"><label>Title<input value={text} onChange={e => setText(e.target.value)} placeholder="e.g. Addition practice"/></label><label>Subject<select value={subject} onChange={e => setSubject(e.target.value)}>{workspace.subjects.map(s => <option key={s}>{s}</option>)}</select></label><label>Due date<input type="date" value={date} onChange={e => setDate(e.target.value)}/></label><label>Instructions<input value={topic} onChange={e => setTopic(e.target.value)} placeholder="What should the child do?"/></label></div><button className="primary" onClick={addHomework}>＋ Assign Homework</button></div><div className="child-list">{workspace.homework.map(h => <article className="child-row" key={h.id}><div><h3>🏠 {h.title}</h3><p>{h.subject} · Due {h.dueDate} · {h.status}</p><span className="child-school">{h.instructions}</span></div><button className="danger" onClick={() => setWorkspace({ ...workspace, homework: workspace.homework.filter(x => x.id !== h.id) })}>Delete</button></article>)}</div></>}
  </section>;
}
